# Generated by Django 5.0.14 on 2026-01-04 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payrolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('cost_center', models.CharField(max_length=100)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='payrolls.payroll')),
            ],
        ),
    ]
